# Generated by Django 4.2.3 on 2023-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='oxygen_cylinder_available',
            field=models.IntegerField(default=0),
        ),
    ]
